import ccxt
import pandas as pd
import time
import requests
from datetime import datetime

# ========== TELEGRAM CONFIGURATION ==========

BOT_TOKEN = "8809200223:AAHmR969mpLw_jEuH2iVeLJ1RcGY8DeosXA"  # Replace with your actual token
CHAT_ID = "503404993"      # Replace with your actual Chat ID

def send_telegram_alert(message):
    """
    Send alert via Telegram Bot API
    """
    try:
        url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
        
        payload = {
            'chat_id': CHAT_ID,
            'text': message,
            'parse_mode': 'HTML',  # Supports bold, italic, etc.
            'disable_notification': False  # Set True for silent messages
        }
        
        response = requests.post(url, json=payload, timeout=10)
        
        if response.status_code == 200:
            print("✅ Telegram alert sent successfully!")
            return True
        else:
            print(f"❌ Telegram error: {response.text}")
            return False
            
    except requests.exceptions.Timeout:
        print("❌ Telegram request timed out")
        return False
    except Exception as e:
        print(f"❌ Telegram error: {e}")
        return False

# Optional: Send formatted message with inline buttons or markdown
def send_telegram_alert_advanced(message):
    """
    Send a more formatted Telegram message with markdown
    """
    try:
        url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
        
        # More detailed formatting
        formatted_message = f"""
<b>🚨 DELTA ALERT</b>

<code>{message}</code>

<b>⏰</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}
<b>🤖</b> Generated by Delta Scanner Bot
        """
        
        payload = {
            'chat_id': CHAT_ID,
            'text': formatted_message,
            'parse_mode': 'HTML',
            'disable_web_page_preview': True
        }
        
        response = requests.post(url, json=payload, timeout=10)
        return response.status_code == 200
        
    except Exception as e:
        print(f"❌ Advanced Telegram error: {e}")
        return False

# ========== YOUR ORIGINAL FUNCTIONS ==========
def fetch_all_delta_india_tickers(exchange):
    """Fetches all active perpetual contracts hosted on the Delta India cluster."""
    raw_markets = exchange.fetch_markets()
    
    tradeable_pairs = []
    for m in raw_markets:
        is_derivative = (
            m.get('swap', False) or 
            m.get('future', False) or 
            m.get('linear', False) or
            (m.get('type') in ['swap', 'future', 'linear'])
        )
        is_active = m.get('active', True)
        
        if is_derivative and is_active:
            symbol = m.get('symbol')
            raw_id = m.get('id', '')
            
            clean_name = raw_id.replace('_', '').replace('-', '').replace('/', '').replace(':', '')
            
            if (symbol, clean_name) not in tradeable_pairs:
                tradeable_pairs.append((symbol, clean_name))
                
    return tradeable_pairs

def scan_momentum(symbol, exchange, timeframe):
    """Fetches historical candles, calculates EMAs, and checks for momentum with Volume + IST Time."""
    try:
        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=300)
        if len(ohlcv) < 200:
            return None
        
        df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        
        df['ema9'] = df['close'].ewm(span=9, adjust=False).mean()
        df['ema20'] = df['close'].ewm(span=20, adjust=False).mean()
        df['ema200'] = df['close'].ewm(span=200, adjust=False).mean()
        
        high_low = df['high'] - df['low']
        high_close = abs(df['high'] - df['close'].shift())
        low_close = abs(df['low'] - df['close'].shift())
        ranges = pd.concat([high_low, high_close, low_close], axis=1)
        true_range = ranges.max(axis=1)
        df['atr'] = true_range.ewm(span=14, adjust=False).mean()
        
        prev_9 = df['ema9'].iloc[-2]
        prev_20 = df['ema20'].iloc[-2]
        curr_9 = df['ema9'].iloc[-1]
        curr_20 = df['ema20'].iloc[-1]
        curr_close = df['close'].iloc[-1]
        curr_200 = df['ema200'].iloc[-1]
        
        candle_body = abs(df['close'].iloc[-1] - df['open'].iloc[-1])
        avg_atr = df['atr'].iloc[-1]
        
        alert_volume = df['volume'].iloc[-1]
        raw_ts = df['timestamp'].iloc[-1]
        
        ist_time = pd.to_datetime(raw_ts, unit='ms', utc=True).tz_convert('Asia/Kolkata')
        formatted_ist = ist_time.strftime('%Y-%m-%d %H:%M:%S IST')
        
        results = {}
        
        is_crossunder = (prev_9 >= prev_20) and (curr_9 < curr_20)
        if is_crossunder and (curr_close < curr_200):
            if candle_body > (avg_atr * 0.5): 
                results['type'] = 'BEARISH BREAKDOWN 📉'
                results['close'] = curr_close
                results['volume'] = alert_volume
                results['time'] = formatted_ist
                results['symbol'] = symbol
                results['timeframe'] = timeframe  
                return results

        is_crossover = (prev_9 <= prev_20) and (curr_9 > curr_20)
        if is_crossover and (curr_close > curr_200):
            if candle_body > (avg_atr * 0.5):
                results['type'] = 'BULLISH BREAKOUT 🚀'
                results['close'] = curr_close
                results['volume'] = alert_volume
                results['time'] = formatted_ist
                results['symbol'] = symbol
                results['timeframe'] = timeframe  
                return results
                
    except Exception as e:
        return None
    return None

# ========== MAIN FUNCTION WITH TELEGRAM INTEGRATION ==========
def main():
    exchange = ccxt.delta({
        'enableRateLimit': True,
        'urls': {
            'api': {
                'public': 'https://api.india.delta.exchange',
                'private': 'https://api.india.delta.exchange',
            }
        }
    })
    
    target_tf = '1h'
    
    print("=" * 60)
    print("🚀 DELTA INDIA SCANNER WITH TELEGRAM ALERTS")
    print("=" * 60)
    print(f"Connecting to Delta India servers...")
    print(f"Target Timeframe: {target_tf}")
    print(f"Telegram alerts will be sent to Chat ID: {CHAT_ID}")
    print("-" * 60)
    
    # Verify Telegram bot is working
    print("🔍 Testing Telegram connection...")
    test_message = "🤖 Delta Scanner Bot is online and ready!"
    send_telegram_alert(test_message)
    print("-" * 60)
    
    pairs = fetch_all_delta_india_tickers(exchange)
    print(f"📊 Total Active Futures Pairs Found: {len(pairs)}")
    print("⚡ Initiating EMA calculation matrix...")
    print("-" * 60)
    
    detected_count = 0
    telegram_sent_count = 0
    
    for ccxt_symbol, app_ticker in pairs:
        time.sleep(0.05)
        setup = scan_momentum(ccxt_symbol, exchange, timeframe=target_tf)
        
        if setup:
            # Format the alert message with emojis and structure
            alert_message = (
                f"🚨 <b>DELTA ALERT</b> | {app_ticker}\n"
                f"📊 {setup['type']}\n"
                f"⏱️ <b>Timeframe:</b> {setup['timeframe']}\n"
                f"💰 <b>Price:</b> {setup['close']:.4f}\n"
                f"📈 <b>Volume:</b> {setup['volume']:.2f}\n"
                f"🕐 <b>Time:</b> {setup['time']}"
            )
            
            # Print to console
            print(alert_message.replace('<b>', '').replace('</b>', ''))
            print("-" * 40)
            
            # Send Telegram alert
            success = send_telegram_alert(alert_message)
            if success:
                telegram_sent_count += 1
            
            detected_count += 1
    
    print("=" * 60)
    print(f"✅ Scan complete!")
    print(f"📊 Total setups found: {detected_count}")
    print(f"📱 Telegram alerts sent: {telegram_sent_count}")
    print("=" * 60)
    
    # Send summary message
    summary = (
        f"✅ <b>Scan Complete</b>\n"
        f"📊 Found: {detected_count} setups\n"
        f"📱 Sent: {telegram_sent_count} alerts\n"
        f"⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}"
    )
    send_telegram_alert(summary)

if __name__ == "__main__":
    print("⚠️  Make sure you have:")
    print("1. Created a Telegram bot via @BotFather")
    print("2. Got your Chat ID from @userinfobot")
    print("3. Added BOT_TOKEN and CHAT_ID to the script")
    print()
    main()