import ccxt
import pandas as pd
import time
import requests
from datetime import datetime

# ========== TELEGRAM CONFIGURATION ==========

BOT_TOKEN = "8809200223:AAHmR969mpLw_jEuH2iVeLJ1RcGY8DeosXA"  # Replace with your actual token
CHAT_ID = "503404993"      # Replace with your actual Chat ID

def send_telegram_alert(message):
    """
    Send alert via Telegram Bot API
    """
    try:
        url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
        
        payload = {
            'chat_id': CHAT_ID,
            'text': message,
            'parse_mode': 'HTML',  # Supports bold, italic, etc.
            'disable_notification': False  # Set True for silent messages
        }
        
        response = requests.post(url, json=payload, timeout=10)
        
        if response.status_code == 200:
            print("✅ Telegram alert sent successfully!")
            return True
        else:
            print(f"❌ Telegram error: {response.text}")
            return False
            
    except requests.exceptions.Timeout:
        print("❌ Telegram request timed out")
        return False
    except Exception as e:
        print(f"❌ Telegram error: {e}")
        return False

# Optional: Send formatted message with inline buttons or markdown
def send_telegram_alert_advanced(message):
    """
    Send a more formatted Telegram message with markdown
    """
    try:
        url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
        
        # More detailed formatting
        formatted_message = f"""
<b>🚨 DELTA ALERT</b>

<code>{message}</code>

<b>⏰</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}
<b>🤖</b> Generated by Delta Scanner Bot
        """
        
        payload = {
            'chat_id': CHAT_ID,
            'text': formatted_message,
            'parse_mode': 'HTML',
            'disable_web_page_preview': True
        }
        
        response = requests.post(url, json=payload, timeout=10)
        return response.status_code == 200
        
    except Exception as e:
        print(f"❌ Advanced Telegram error: {e}")
        return False

# ========== YOUR ORIGINAL FUNCTIONS ==========
# it will scan all derivatives, including call/put options, futures, and perpetual swaps.
# def fetch_all_delta_india_tickers(exchange):
#     """Fetches all active perpetual contracts hosted on the Delta India cluster."""
#     raw_markets = exchange.fetch_markets()
    
#     tradeable_pairs = []
#     for m in raw_markets:
#         is_derivative = (
#             m.get('swap', False) or 
#             m.get('future', False) or 
#             m.get('linear', False) or
#             (m.get('type') in ['swap', 'future', 'linear'])
#         )
#         is_active = m.get('active', True)
        
#         if is_derivative and is_active:
#             symbol = m.get('symbol')
#             raw_id = m.get('id', '')
            
#             clean_name = raw_id.replace('_', '').replace('-', '').replace('/', '').replace(':', '')
            
#             if (symbol, clean_name) not in tradeable_pairs:
#                 tradeable_pairs.append((symbol, clean_name))
                
#     return tradeable_pairs

# it will not scan call put options, only futures and perpetual swaps.
def fetch_all_delta_india_tickers(exchange):
    """Fetches all active perpetual contracts hosted on the Delta India cluster."""
    raw_markets = exchange.fetch_markets()
    
    tradeable_pairs = []
    for m in raw_markets:
        # 1. Identify standard derivatives
        is_derivative = (
            m.get('swap', False) or 
            m.get('future', False) or 
            m.get('linear', False) or
            (m.get('type') in ['swap', 'future', 'linear'])
        )
        is_active = m.get('active', True)
        
        # 2. EXPLICITLY BAN CALL/PUT OPTIONS
        is_option = m.get('option', False) or (m.get('type') == 'option')

        # # 3. VERIFY QUOTE CURRENCY IS EITHER USDT OR USD
        # quote = m.get('quote', '').upper()
        # is_usd_or_usdt = (quote == 'USDT' or quote == 'USD')
        
        # # Only pass if it fits all rules
        # if is_derivative and is_active and not is_option and is_usd_or_usdt:
        
        # Only pass if it IS a derivative, IS active, and IS NOT an option
        if is_derivative and is_active and not is_option:
            symbol = m.get('symbol')
            raw_id = m.get('id', '')
            
            clean_name = raw_id.replace('_', '').replace('-', '').replace('/', '').replace(':', '')
            
            if (symbol, clean_name) not in tradeable_pairs:
                tradeable_pairs.append((symbol, clean_name))
                
    return tradeable_pairs

def format_volume(volume):
    """Formats raw volume into human-readable K, M, B units."""
    if volume is None:
        return "0.00"
    
    if volume >= 1_000_000_000:
        return f"{volume / 1_000_000_000:.2f}B"
    elif volume >= 1_000_000:
        return f"{volume / 1_000_000:.2f}M"
    elif volume >= 1_000:
        return f"{volume / 1_000:.2f}K"
    else:
        return f"{volume:.2f}"

def scan_momentum(symbol, exchange, timeframe):
    """Fetches historical candles, calculates EMAs, and checks for momentum with Volume + IST Time."""
    try:
        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=300)
        if len(ohlcv) < 200:
            return None
        
        df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        
        df['ema9'] = df['close'].ewm(span=9, adjust=False).mean()
        df['ema20'] = df['close'].ewm(span=20, adjust=False).mean()
        df['ema200'] = df['close'].ewm(span=200, adjust=False).mean()
        
        high_low = df['high'] - df['low']
        high_close = abs(df['high'] - df['close'].shift())
        low_close = abs(df['low'] - df['close'].shift())
        ranges = pd.concat([high_low, high_close, low_close], axis=1)
        true_range = ranges.max(axis=1)
        df['atr'] = true_range.ewm(span=14, adjust=False).mean()
        
        prev_9 = df['ema9'].iloc[-2]
        prev_20 = df['ema20'].iloc[-2]
        curr_9 = df['ema9'].iloc[-1]
        curr_20 = df['ema20'].iloc[-1]
        curr_close = df['close'].iloc[-1]
        curr_200 = df['ema200'].iloc[-1]
        
        candle_body = abs(df['close'].iloc[-1] - df['open'].iloc[-1])
        avg_atr = df['atr'].iloc[-1]
        
        alert_volume = df['volume'].iloc[-1]
        raw_ts = df['timestamp'].iloc[-1]
        
        ist_time = pd.to_datetime(raw_ts, unit='ms', utc=True).tz_convert('Asia/Kolkata')
        formatted_ist = ist_time.strftime('%Y-%m-%d %H:%M:%S IST')
        
        is_crossunder = (prev_9 >= prev_20) and (curr_9 < curr_20)
        is_crossover = (prev_9 <= prev_20) and (curr_9 > curr_20)
        
        alert_type = None
        if is_crossunder and (curr_close < curr_200) and (candle_body > (avg_atr * 0.5)):
            alert_type = 'BEARISH BREAKDOWN 📉'
        elif is_crossover and (curr_close > curr_200) and (candle_body > (avg_atr * 0.5)):
            alert_type = 'BULLISH BREAKOUT 🚀'

        if alert_type:
            # Safely fetch 24h rolling details via fast ticker API
            try:
                ticker_data = exchange.fetch_ticker(symbol)
                vol_24h = ticker_data.get('quoteVolume') or ticker_data.get('baseVolume', 0.0)
            except Exception:
                vol_24h = 0.0

            results = {
                'type': alert_type,
                'close': curr_close,
                'volume': alert_volume,
                'vol_24h': vol_24h,
                'time': formatted_ist,
                'symbol': symbol,
                'timeframe': timeframe  
            }
            return results
                
    except Exception as e:
        return None
    return None

# ========== MAIN FUNCTION WITH TELEGRAM INTEGRATION ==========
def main(target_tf='15m'):
    exchange = ccxt.delta({
        'enableRateLimit': True,
        'urls': {
            'api': {
                'public': 'https://api.india.delta.exchange',
                'private': 'https://api.india.delta.exchange',
            }
        }
    })
    
    # target_tf = '15m'
    target_tf = target_tf
    
    print("=" * 60)
    print("🚀 DELTA INDIA SCANNER WITH TELEGRAM ALERTS")
    print("=" * 60)
    print(f"Connecting to Delta India servers...")
    print(f"Target Timeframe: {target_tf}")
    print(f"Telegram alerts will be sent to Chat ID: {CHAT_ID}")
    print("-" * 60)
    
    # Verify Telegram bot is working
    print("🔍 Testing Telegram connection...")
    test_message = "🤖 Delta Scanner Bot is online and ready!"
    send_telegram_alert(test_message)
    print("-" * 60)
    
    # 1. Define your high-priority coins here (use uppercase base symbols)
    PRIORITY_COINS = ['BTC', 'ETH', 'SOL', 'XRP', 'AAVE', 'LINK', 'XAUT', 'AVAX']

    pairs = fetch_all_delta_india_tickers(exchange)
    print(f"📊 Total Active Futures Pairs Found: {len(pairs)}")
    
    # 2. Separate the pairs into Priority and Normal pools
    priority_pairs = []
    normal_pairs = []
    
    for ccxt_symbol, app_ticker in pairs:
        # Extract the base coin (e.g., gets 'BTC' from 'BTC/USDT:USDT')
        base_asset = ccxt_symbol.split('/')[0].upper() if '/' in ccxt_symbol else app_ticker
        
        # Check if this coin matches anything in your priority list
        if base_asset in PRIORITY_COINS:
            priority_pairs.append((ccxt_symbol, app_ticker))
        else:
            normal_pairs.append((ccxt_symbol, app_ticker))
            
    # 3. Combine them: Priority pairs will be scanned first
    final_pairs_list = priority_pairs + normal_pairs
    
    print(f"⭐ High Priority Pairs to scan first: {len(priority_pairs)}")
    print(f"📦 Remaining Pairs to scan next: {len(normal_pairs)}")
    print("⚡ Initiating EMA calculation matrix...")
    print("-" * 60)
    
    detected_count = 0
    telegram_sent_count = 0
    
    # 4. Loop through the rearranged list
    for ccxt_symbol, app_ticker in final_pairs_list:
        time.sleep(0.05)
        setup = scan_momentum(ccxt_symbol, exchange, timeframe=target_tf)
        
        # if setup:
        #     # Format the alert message with emojis and structure
        #     alert_message = (
        #         f"🚨 <b>DELTA ALERT</b> | {app_ticker}\n"
        #         f"📊 {setup['type']}\n"
        #         f"⏱️ <b>Timeframe:</b> {setup['timeframe']}\n"
        #         f"💰 <b>Price:</b> {setup['close']:.4f}\n"
        #         f"📈 <b>Volume:</b> {setup['volume']:.2f}\n"
        #         f"🕐 <b>Time:</b> {setup['time']}"
        #     )

        if setup:
            # Format both the candle volume and the 24h rolling volume
            readable_volume = format_volume(setup['volume'])
            readable_24h_vol = format_volume(setup.get('vol_24h', 0.0))
            
            # Format the alert message with emojis and structure
            alert_message = (
                f"🚨 <b>DELTA ALERT</b> | {app_ticker}\n"
                f"📊 {setup['type']}\n"
                f"⏱️ <b>Timeframe:</b> {setup['timeframe']}\n"
                f"💰 <b>Price:</b> {setup['close']:.4f}\n"
                f"⚡ <b>Candle Vol:</b> {readable_volume}\n"
                f"🌊 <b>24h Volume:</b> ${readable_24h_vol}\n"
                f"🕐 <b>Time:</b> {setup['time']}"
            )
            
            # Print to console
            print(alert_message.replace('<b>', '').replace('</b>', ''))
            print("-" * 40)
            
            # Send Telegram alert
            success = send_telegram_alert(alert_message)
            if success:
                telegram_sent_count += 1
            
            detected_count += 1
    
    print("=" * 60)
    print(f"✅ Scan complete!")
    print(f"📊 Total setups found: {detected_count}")
    print(f"📱 Telegram alerts sent: {telegram_sent_count}")
    print("=" * 60)
    
    # Send summary message
    summary = (
        f"✅ <b>Scan Complete</b>\n"
        f"📊 Found: {detected_count} setups\n"
        f"📱 Sent: {telegram_sent_count} alerts\n"
        f"⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}"
    )
    send_telegram_alert(summary)

if __name__ == "__main__":
    main(target_tf='15m')

# # For GithubActions
# if __name__ == "__main__":
#     # Continuous live loop structure for persistent web environments
#     INTERVAL_SECONDS = 900 # 15 minutes
    
#     print("🌍 Hugging Face Container Engine Initialized Successfully.")
#     while True:
#         start_time = time.time()
#         current_run_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')
#         print(f"🔄 Executing active scanning cycle at: {current_run_time}")
        
#         try:
#             # Invokes your main matrix engine with 15-minute candles
#             main(target_tf='15m')
#         except Exception as e:
#             print(f"⚠️ Runtime execution error caught in main loop iteration: {e}")
            
#         # Calculate process time to avoid interval drift
#         elapsed_time = time.time() - start_time
#         remaining_sleep = max(1, INTERVAL_SECONDS - elapsed_time)
        
#         print(f"😴 Cycle complete. Processing took {elapsed_time:.1f}s. Sleeping for {remaining_sleep:.1f}s...")
#         time.sleep(remaining_sleep)
